name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


PROJECT_NAME = Train_Ticket_Booking_System.exe
DO_IT =  SRC/compute.c SRC/display.c SRC/cancel.c SRC/charge.c SRC/login.c SRC/printticket.c SRC/reservation.c SRC/specifictrain.c SRC/viewDetails.c SRC/validate.c unity/unity.c SRC/present.c 
$(PROJECT_NAME) : $(SRC) 
jobs:
  build:gcc Main.c  -I -c $(DO_IT)  -o $(PROJECT_NAME)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
